### PR TITLE
Tweaks

### LINKED ISSUE #28: Fetch and Display Data through Product Card in Home Page using Supabase API
### Description

We have successfully created the product card component, and the next step is to retrieve data from the database using the Supabase API and populate the product card with the fetched information. This task involves connecting the existing product card UI with the Supabase API to seamlessly display product details.

### Requirements

- Implement logic to fetch product data from the database using the Supabase API.
- Integrate the fetched product data with the product card component.
- Populate the product card UI with relevant product details, such as images, titles, and other attributes.

### Dependencies

This task requires integration with the Supabase API for data retrieval.

### PR DESCRIPTION
**Pull request by danicunhac**
In this PR I'm making a few tweaks to the project, including styling, configurations and fixes.
- Changes to the header items.

Screenshot 2023-08-12 at 16 09 14

### CODE REVIEW

**Comment by mirsahib** [comment]
Hey @danicunhac  could you please review the PR #30, i have integrated the api for the home page and this PR will create conflict  with mine

**Comment by danicunhac** [comment]
> Hey @danicunhac could you please review the PR #30, i have integrated the api for the home page and this PR will create conflict with mine

I've removed the integration I did to keep only the minor changes

**Comment by juancmandev** [comment]
Before:

Screenshot 2023-08-12 at 11 35 27 a m

After:

Screenshot 2023-08-12 at 11 43 51 a m
Screenshot 2023-08-12 at 11 44 00 a m

Change the Supabase instance for the new one in client components.

`import { createClientComponentClient } from '@supabase/auth-helpers-nextjs';`

For preventing this warning:

Screenshot 2023-08-12 at 11 35 50 a m

**Comment by danicunhac** [comment]
Nice @juancmandev ! I was thinking the font size could shrink in order to maintain the same height, but I'm unsure how to do that.

**Comment by juancmandev** [comment]
With tailwind: `line-clamp-x` x the number of lines you want to show, in this case just 1

**Comment by danicunhac** [comment]
`line-clamp-x` doesn't shrink the text, it just handles the overflow by adding ellipsis

**Comment by juancmandev** [comment]
Yeah, in this case is for just limit the lines of text and prevent cards with different height

**Review by juanmanzanero-com — APPROVED** [review]

**Pull request closed without merging**
